name: Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    name: Build Workspace on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, ubuntu-24.04-arm]
        # os: [ubuntu-latest]
      fail-fast: false

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set Rust linker for Linux
        if: matrix.os == 'ubuntu-latest' || matrix.os == 'ubuntu-24.04-arm'
        run: |
          echo "RUSTFLAGS=-C linker=gcc" >> $GITHUB_ENV

      - name: Install cargo-llvm-cov
        run: cargo install cargo-llvm-cov --force

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      # Linux-specific build tools
      - name: Install build essentials (Ubuntu)
        if: matrix.os == 'ubuntu-latest' || matrix.os == 'ubuntu-24.04-arm'
        run: sudo apt-get update && sudo apt-get install -y build-essential pkg-config libssl-dev python3-dev libpam0g-dev libffi-dev libc6-dev llvm clang lld python3.12 python3.12-dev

      - name: Prepare PyO3 env
        run: |
          echo "PYO3_CONFIG_FILE=$(pwd)/pyo3.cfg" >> $GITHUB_ENV
          echo "version=3.12" > pyo3.cfg

      - name: Fix Linker on Ubuntu
        if: matrix.os == 'ubuntu-latest' || matrix.os == 'ubuntu-24.04-arm'
        run: |
          export LD_LIBRARY_PATH=$(python3.12-config --prefix)/lib:$LD_LIBRARY_PATH
          export PYTHON_SYS_EXECUTABLE=$(which python3.12)

      - name: Coverage
        run: |
          cargo llvm-cov --all-features --workspace --lcov --output-path lcov.info --locked

      - name: Upload coverage
        uses: codecov/codecov-action@v6
        with:
          files: lcov.info
          flags: ${{ matrix.os }}
          token: ${{secrets.CODECOV_TOKEN}}
